### PR TITLE
Allow script to work on Ubuntu 22.04 LTS

### PR DESCRIPTION
**Pull request by timotheosh**
Allow script to work on Ubuntu 22.04 LTS

### CODE REVIEW

**Comment by 64kramsystem** [comment]
Wow, great to see that it works without changes :star_struck:  On which Ubuntu distro did you run it?

**Comment by timotheosh** [comment]
I've run it several times successfully with Ubuntu Server, and Kubuntu 22.04. Let me know if you'd rather have some test results with the vanilla desktop installer.

**Comment by 64kramsystem** [comment]
Thanks! I think that should be fine. KUbuntu actuallyy has some extra steps, so we can reasonably assume that if it works on Kubuntu, it should also work on Ubuntu. I'm going to test the base Ubuntu anyway.

**Comment by 64kramsystem** [comment]
Thanks for the contribution! :smile:

**Pull request merged**
